[font]
normal = { family = "MesloLGS NF", style = "Regular" }
size = 18
[window]
opacity=0.8
blur=true
[keyboard]
bindings = [
  {key="C", mods="Control|Shift", action="Copy"},
  {key="V", mods="Control|Shift", action="Paste"},
]
