[font]
normal = { family = "MesloLGL NerdFont", style = "Regular" }
size = 12

[window]
dimensions = { columns = 140, lines = 30 }
opacity = 1.0
blur = true

[keyboard]
bindings = [
  { key="C", mods="Control|Shift", action="Copy" },
  { key="V", mods="Control|Shift", action="Paste" },
  { key="N", mods="Control", action="SpawnNewInstance" },
  { key="T", mods="Control|Shift", command={ program = "zsh", args = [ "-c", "~/scripts/toggle-opacity.sh" ] } },
]

[mouse]
hide_when_typing = true
